version: "3"
services:
  db:
    image: postgres:11.0
    env_file:
      - .env
    volumes:
      - ./Docker/pgsql/conf:/etc/postgresql/:rw
      - ./Docker/pgsql/data:/data/postgres
    ports:
      - 6666:5432
    networks:
      - webnet

  pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: "none"
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8182:80
    networks:
      - webnet
      
networks:
  webnet:
    driver: overlay
